import Head from 'next/head'

export default function Home() {
  return (
    <>

      <Head>
        <title>Next Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section>
        <h1 className='text-4xl mb-5 font-semibold'>Example Page</h1>
      </section>

    </>
  )
}
